spring:
  application:
    name: ShoppingCart
  datasource:
    url: jdbc:h2:mem:shoppingcartdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 5

  level:
    root: INFO
    com.example: DEBUG

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  threshold:
    console: OFF